---
title: Nowcast Daily Outline
author:
  - name: Jessalyn Sebastian
    corresponding: false
    email: xxx
    roles:
      - xxx
    affiliations:
      - xxx
  - name: Sam Abbott
    corresponding: false
    email: xxx
    roles:
      - xxx
    affiliations:
      - xxx
  - name: Katelyn Gostic
    corresponding: false
    email: xxx
    roles:
      - xxx
    affiliations:
      - xxx
keywords:
  - xxx
abstract: |
  xxx
plain-language-summary: |
  xxx
key-points:
  - xxx
date: last-modified
bibliography: "references.bib"
citation:
  container-title: xxx
number-sections: true
---

## Introduction

Infectious disease outbreaks pose significant challenges to public health authorities, necessitating accurate and timely estimation of metrics like counts of hospital admissions. Nowcasting is the real-time estimation of such metrics, with adjustment for reporting delays. The granularity of these nowcasts plays a pivotal role; finer resolutions - for example, daily nowcasts as opposed to weekly - offer a more detailed understanding of the outbreak's dynamics and aid in predicting healthcare demands with greater precision. 

A significant challenge in nowcasting lies in navigating the complexities of reporting cycles. Much of the nowcasting literature tends to assume that event and report processes occur with the same temporal resolution; for example, daily event dates with daily report dates. It is a common problem, however, to have report times with lower resolution than event times. The case we focus on in this report is the case of a fixed weekly reporting schedule, in which event data is given with daily resolution, but are reported once per week on a fixed day.

Within the framework of the `R` package `epinowcast`, we evaluate a few possible methods for nowcasting hospital admissions daily with a weekly reporting cycle. 

## Methods {#sec-methods}

TODO: Flesh out outline of reporting cycle explanation.

[Here: figure that illustrates the issue, reporting triangle?]

Using `epinowcast` (details below), we will compare four different methods for nowcasting a fixed weekly reporting cycle with daily resolution:

1. A model with a fixed day-of-week (DOW) reporting effect

2. A model with a fixed effect hardcoded such that the reporting hazard for non-report days is approximately zero

3.  A model which aggregates reporting probabilities and places them on only reporting days


All of these are described in further detail below.

### Modeling {#sec-modeling}

The `epinowcast` package in `R` is designed as a versatile framework for monitoring infectious diseases in real-time. It is an extension of the model developed by Günther et al. in _Nowcasting the COVID-19 pandemic in Bavaria._ [@guntheretal], which itself was an extension of the model proposed by Höhle and Heiden [@hohleandheiden] that uses a Bayesian hierarchical model with a discrete time survival model for the reporting delay distribution.

All three `epinowcast` models we will compare share very similar frameworks. The instantaneous growth rate $r_t$, defined as the log of the expected number of final observed hospital admissions between times $t$ and $t-1$, is modeled with a daily random walk:

$$\log r_1 \sim N(r_0, \sigma_1^2); \hspace{1em} \log r_t\mid r_{t-1} \sim N(\log r_{t-1}, \sigma^2)$$

And the expected final number of admissions for a admission day $t$, $\lambda_t = E[N_t]$, is given by

$$\lambda_1\sim\text{LogNormal}(\mu_\ell, \sigma_\ell); \hspace{1em} \lambda_t = r_t\lambda_{t-1}; \hspace{1em} t = 1,\dots T$$

where $T$ is the latest admission date. The delay distribution is parameterized with a discrete-time hazard model. Delay probabilities, given by $p_{t,d}$, are converted to hazards:

\begin{align}
  h_{t,d} &= P(\text{delay} = d \mid \text{delay} \geq d, W_{t,d}) \\
    &= p_{t,d}\bigg(1-\sum_{i=0}^{d-1} p_{t,i}\bigg)^{-1} \hspace{1em} t = 1,\dots T, d = 0,\dots D
\end{align}

where $D$ is the maximum possible delay, and $W_{t,d}$ is the design matrix that encodes the baseline delay distribution and the admission and report date covariate effects on the hazard. This can then be modeled via a logistic regression in a discrete-time hazard model

$$\text{logit}(h_{t,d}) = \gamma_{t,d} + \delta_0 + \beta_{f,\delta}X_\delta; \hspace{1em} t = 1,\dots T, d = 0,\dots D$$

where $\gamma_{t,d}$ represents the baseline hazard, for which we use a gamma distribution. The gamma distribution is discretized and adjusted for the maximum possible delay, $D$, to obtain parametric report probabilities $p'_{t,d}$. These are then converted to logit hazards as $\gamma_{t,d} = p_{t,d}\big(1-\sum_{i=0}^{d-1} p_{t,i}\big)^{-1}$.

A negative binomial likelihood is used to model notifications for each reference date $t$ and delay $d$,

$$n_{t,d}\mid \lambda_t, p_{t,d} \sim \text{NegBin}(\lambda_t p_{t,d}, \phi); \hspace{1em} t = 1,\dots T, d = 0,\dots D$$

$$\frac{1}{\sqrt{\phi}} \sim \text{Half-Normal}(0,1)$$

and finally we have 

$$N_t = \sum_{d=0}^D n_{t,d}$$


#### DOW Fixed Effect Model {#sec-model1}

One simple way to handle the weekly reporting cycle is to place a reporting day-of-week fixed effect on the logit hazard. In the base model from @sec-modeling we can specify $\beta_{f,\delta} X_\delta$ as

$$\beta_1\mathbb{1}\{t+d = 
\text{Monday}\} + \beta_2\mathbb{1}\{t+d = 
\text{Tuesday}\} + \dots + \beta_7\mathbb{1}\{t+d = 
\text{Sunday}\}$$

The model will infer which day is the weekly reporting day from the data, and the coefficients of all the other day-of-week fixed effects will be inferred to be negative values large enough to make the hazard $h_{t,d}$ approximately zero, since there is no reporting probability for non-reporting days.


#### Hardcoded Fixed Effect Model {#sec-model2}

To improve efficiency and convergence of the model, we can modify the above in @sec-model1 so that `epinowcast` need not infer the reporting day, since it is already known. The same reporting effect on the hazard $\beta_{f, \delta} X_\delta$ from @sec-modeling can be hardcoded as

$$\beta_1 \mathbb{1}\{t+d \neq \text{Report Day}\}; \hspace{1em} \beta_1 = -20$$

This way, report dates which are not the weekly reporting day are explicitly modeled as having approximately zero reporting hazard.

#### Aggregated Reporting Probability Model {#sec-model3}

Instead of modifying the hazard, we can directly aggregate reporting probabilities to only reporting days. After daily reporting hazards $h_{t,d}$ are converted to daily reporting probabilities $p_{t,d}$, they can be summed

TODO: probability agg method in math

This process mimics more closely the reporting process that is occurring in reality, in which hospital admissions are entered into a database throughout the week and all admissions that have been entered before the reporting day are reported on the reporting day.

### Simulated Scenario

One outbreak scenario was simulated from a stochastic SEIHRD model (Susceptible - Exposed - Infected - Hospitalized - Recovered - Dead). Hospital admission reporting delays were simulated from a gamma distribution and with a weekend effect. Parameters which governed the simulation process are given in the table below.

|Parameter | Description | Value |
|----------|-------------|-------|
|$N$ | Population size | $5\times 10^4$ |
|$\beta$ | Transmission rate per contact | $3/5$ |
|$1/\gamma$ | Mean latent period duration (days) | $3$ |
|$1/\nu$ | Mean infectious period duration (days) | $5$ |
|$1/\eta$ | Mean hospital stay duration (days) | $6$ |
|$1/\kappa$ | Mean duration of immunity (days) | $30$ |
|$\tau$ | Infection-Hospitalization ratio | $1/10$ |
|$v$ | Hospitalization-fatality ratio | $1/10$ |
|$k$ | Gamma reporting delay shape parameter | $3/2$ |
|$\theta$ | Gamma reporting delay scale parameter | $3$ |

These synthetic data are available entirely with daily resolution, including reporting dates (Daily/Daily data), which is not possible with the real data. They can be aggregated to daily admission data with weekly reporting data (Daily/Weekly), and to weekly admission data with weekly reporting data (Weekly/Weekly).

### Real Data

The real data is Daily/Weekly influenza hospital admission data from [RESP-NET](https://www.cdc.gov/resp-net/dashboard/index.html), the Respiratory Virus Hospitalization Surveillance Network. These surveillance data are collected from counties in 14 states, accounting for about 10% of the U.S. propulation. We use data from the 2021-2022 and 2022-2023 flu seasons, and run nowcasts across a series of reporting dates from those seasons to compare Weekly/Weekly models (the baseline) with Daily/Weekly models.

## Results

TODO: Deeper outline of results section

### Evaluation

We compare performance of nowcasts using proper scoring rules [@czadoetal], which will evaluate both the calibration (accuracy) and the sharpness (precision) of the nowcasts.

### Simulated Scenario

[Here: visual comparison of Daily/Daily with Daily/Weekly, since this can only be done w/ sim data]

### Real Data

[Here: example visual Daily/Weekly nowcast + visual comparison of Daily/Weekly nowcast aggregated to weekly and Weekly/Weekly]

[Here: scoring of Daily/Weekly vs. scoring of Weekly/Weekly]

## Conclusions

### Limitations and Further Work

## References {.unnumbered}

::: {#refs}
:::